// Meditaire 기본 카드팩
// 카드 형식: { text, category, tags[] } — 두 카드의 tag가 하나라도 겹치면 연결된다.
// tagLabels: 연결 성공 시 "공통 고리"로 보여줄 한글 설명.
window.MEDITAIRE_PACKS = [
  {
    id: 'anemia',
    name: '빈혈',
    subject: '혈액종양내과',
    tagLabels: {
      iron_def: '철결핍빈혈',
      microcytic: '소구성 빈혈',
      acd: '만성질환빈혈',
      thal: '지중해빈혈',
      megaloblastic: '거대적혈모구빈혈',
      b12: '비타민 B12 결핍',
      folate: '엽산 결핍',
      hemolysis: '용혈',
      aiha: '자가면역 용혈빈혈',
      hs: '유전구상적혈구증',
      g6pd: 'G6PD 결핍증',
      aplastic: '재생불량빈혈',
      pnh: '발작성 야간혈색소뇨증(PNH)'
    },
    cards: [
      { text: '철결핍빈혈', category: '질환', tags: ['iron_def', 'microcytic'] },
      { text: 'MCV < 80 fL', category: '검사소견', tags: ['microcytic'] },
      { text: '페리틴 감소', category: '검사소견', tags: ['iron_def'] },
      { text: 'TIBC 증가', category: '검사소견', tags: ['iron_def'] },
      { text: '만성 위장관 출혈', category: '원인', tags: ['iron_def'] },
      { text: '숟가락손톱 (koilonychia)', category: '임상상', tags: ['iron_def'] },
      { text: '경구 철분제', category: '치료', tags: ['iron_def'] },
      { text: '지중해빈혈', category: '질환', tags: ['thal', 'microcytic'] },
      { text: '표적세포 (target cell)', category: '검사소견', tags: ['thal'] },
      { text: 'HbA2 증가 (β-지중해빈혈 보인자)', category: '진단', tags: ['thal'] },
      { text: 'Mentzer index < 13', category: '검사소견', tags: ['thal', 'microcytic'] },
      { text: '만성질환빈혈', category: '질환', tags: ['acd', 'microcytic'] },
      { text: '헵시딘 증가', category: '병태생리', tags: ['acd'] },
      { text: '페리틴 정상~증가, TIBC 감소', category: '검사소견', tags: ['acd'] },
      { text: '거대적혈모구빈혈', category: '질환', tags: ['megaloblastic', 'b12', 'folate'] },
      { text: 'MCV > 100 fL', category: '검사소견', tags: ['megaloblastic'] },
      { text: '과분엽 호중구', category: '검사소견', tags: ['megaloblastic'] },
      { text: '비타민 B12 결핍', category: '원인', tags: ['megaloblastic', 'b12'] },
      { text: '엽산 결핍', category: '원인', tags: ['megaloblastic', 'folate'] },
      { text: '위절제술 병력', category: '위험인자', tags: ['b12', 'iron_def'] },
      { text: '악성빈혈 (항내인자 항체)', category: '원인', tags: ['b12'] },
      { text: '아급성 연합 변성 (SCD)', category: '임상상', tags: ['b12'] },
      { text: '메틸말론산(MMA) 증가', category: '검사소견', tags: ['b12'] },
      { text: '호모시스테인 증가', category: '검사소견', tags: ['b12', 'folate'] },
      { text: '메토트렉세이트 · 임신 · 알코올', category: '위험인자', tags: ['folate'] },
      { text: '용혈빈혈', category: '질환', tags: ['hemolysis'] },
      { text: '간접 빌리루빈 · LDH 증가', category: '검사소견', tags: ['hemolysis'] },
      { text: '합토글로빈 감소', category: '검사소견', tags: ['hemolysis'] },
      { text: '망상적혈구 증가', category: '검사소견', tags: ['hemolysis'] },
      { text: '자가면역 용혈빈혈', category: '질환', tags: ['aiha', 'hemolysis'] },
      { text: '직접 Coombs 검사 양성', category: '진단', tags: ['aiha'] },
      { text: '구상적혈구 (말초혈액도말)', category: '검사소견', tags: ['aiha', 'hs'] },
      { text: '스테로이드', category: '치료', tags: ['aiha'] },
      { text: '유전구상적혈구증', category: '질환', tags: ['hs', 'hemolysis'] },
      { text: 'MCHC 증가', category: '검사소견', tags: ['hs'] },
      { text: 'EMA 결합 감소 · 삼투압 취약성 증가', category: '진단', tags: ['hs'] },
      { text: '비장절제술', category: '치료', tags: ['hs'] },
      { text: 'G6PD 결핍증', category: '질환', tags: ['g6pd', 'hemolysis'] },
      { text: '하인즈 소체 · 물린 세포 (bite cell)', category: '검사소견', tags: ['g6pd'] },
      { text: '잠두 · 설파제 · 프리마퀸', category: '위험인자', tags: ['g6pd'] },
      { text: 'X염색체 연관 열성 유전', category: '원인', tags: ['g6pd'] },
      { text: '재생불량빈혈', category: '질환', tags: ['aplastic'] },
      { text: '범혈구감소 + 망상적혈구 감소', category: '검사소견', tags: ['aplastic'] },
      { text: '저세포성 골수 (지방 대치)', category: '진단', tags: ['aplastic'] },
      { text: 'ATG + 사이클로스포린 / 조혈모세포이식', category: '치료', tags: ['aplastic'] },
      { text: 'PNH', category: '질환', tags: ['pnh', 'hemolysis', 'aplastic'] },
      { text: '유세포분석: CD55 · CD59 결손', category: '진단', tags: ['pnh'] },
      { text: '에쿨리주맙', category: '치료', tags: ['pnh'] },
      { text: '정맥혈전증 (Budd-Chiari)', category: '합병증', tags: ['pnh'] }
    ]
  },
  {
    id: 'thyroid',
    name: '갑상선',
    subject: '내분비내과',
    tagLabels: {
      hyper: '갑상선중독증',
      graves: '그레이브스병',
      atd: '항갑상선제',
      rai_up: '방사성요오드 섭취 증가',
      rai_down: '방사성요오드 섭취 감소',
      subacute: '아급성 갑상선염',
      hypo: '갑상선기능저하증',
      hashimoto: '하시모토 갑상선염',
      thyroid_ca: '갑상선암',
      papillary: '유두암',
      follicular: '여포암',
      medullary: '수질암',
      men2: 'MEN 2'
    },
    cards: [
      { text: '그레이브스병', category: '질환', tags: ['graves', 'hyper'] },
      { text: 'TSH 수용체 항체 (TRAb)', category: '진단', tags: ['graves'] },
      { text: '안구돌출', category: '임상상', tags: ['graves'] },
      { text: '전경골 점액부종', category: '임상상', tags: ['graves'] },
      { text: '미만성 RAI 섭취 증가', category: '검사소견', tags: ['graves', 'rai_up'] },
      { text: '독성 다결절갑상선종', category: '질환', tags: ['hyper', 'rai_up'] },
      { text: '독성 선종 (hot nodule)', category: '질환', tags: ['hyper', 'rai_up'] },
      { text: '방사성요오드 치료', category: '치료', tags: ['graves', 'rai_up'] },
      { text: 'TSH 감소, free T4 증가', category: '검사소견', tags: ['hyper'] },
      { text: '빈맥 · 체중감소 · 열불내성', category: '임상상', tags: ['hyper'] },
      { text: '베타차단제', category: '치료', tags: ['hyper'] },
      { text: '갑상선 폭풍', category: '합병증', tags: ['hyper'] },
      { text: '메티마졸', category: '치료', tags: ['atd', 'graves'] },
      { text: 'PTU (임신 1분기)', category: '치료', tags: ['atd'] },
      { text: '무과립구증', category: '합병증', tags: ['atd'] },
      { text: '간독성 (PTU)', category: '합병증', tags: ['atd'] },
      { text: '아급성 갑상선염', category: '질환', tags: ['subacute', 'hyper', 'rai_down'] },
      { text: '압통 있는 갑상선 + ESR 상승', category: '임상상', tags: ['subacute'] },
      { text: '선행 상기도 바이러스 감염', category: '원인', tags: ['subacute'] },
      { text: 'NSAIDs · 스테로이드', category: '치료', tags: ['subacute'] },
      { text: 'RAI 섭취 감소', category: '검사소견', tags: ['rai_down'] },
      { text: '무통성 · 산후 갑상선염', category: '질환', tags: ['rai_down', 'hyper', 'hashimoto'] },
      { text: '외인성 갑상선호르몬 복용 (thyroglobulin 감소)', category: '원인', tags: ['rai_down', 'hyper'] },
      { text: '하시모토 갑상선염', category: '질환', tags: ['hashimoto', 'hypo'] },
      { text: '항TPO 항체', category: '진단', tags: ['hashimoto'] },
      { text: '원발성 갑상선 림프종', category: '합병증', tags: ['hashimoto'] },
      { text: 'TSH 증가, free T4 감소', category: '검사소견', tags: ['hypo'] },
      { text: '추위불내성 · 체중증가 · 서맥', category: '임상상', tags: ['hypo'] },
      { text: '고콜레스테롤혈증 · CK 증가', category: '검사소견', tags: ['hypo'] },
      { text: '레보티록신', category: '치료', tags: ['hypo', 'thyroid_ca'] },
      { text: '점액부종 혼수', category: '합병증', tags: ['hypo'] },
      { text: '세침흡인검사 (FNA)', category: '진단', tags: ['thyroid_ca'] },
      { text: '갑상선 전절제술', category: '치료', tags: ['thyroid_ca', 'graves'] },
      { text: '갑상선 유두암', category: '질환', tags: ['papillary', 'thyroid_ca'] },
      { text: '모래알 소체 (psammoma body)', category: '검사소견', tags: ['papillary'] },
      { text: '간유리 핵 · 핵구 (Orphan Annie)', category: '검사소견', tags: ['papillary'] },
      { text: '림프절 전이', category: '병태생리', tags: ['papillary'] },
      { text: '두경부 방사선 노출', category: '위험인자', tags: ['papillary'] },
      { text: '갑상선 여포암', category: '질환', tags: ['follicular', 'thyroid_ca'] },
      { text: '피막 · 혈관 침범', category: '진단', tags: ['follicular'] },
      { text: '혈행성 전이 (폐 · 뼈)', category: '병태생리', tags: ['follicular'] },
      { text: '갑상선 수질암', category: '질환', tags: ['medullary', 'thyroid_ca', 'men2'] },
      { text: '칼시토닌 증가', category: '검사소견', tags: ['medullary'] },
      { text: '부여포세포 (C cell) 기원', category: '병태생리', tags: ['medullary'] },
      { text: 'RET 유전자 변이', category: '원인', tags: ['medullary', 'men2'] },
      { text: '갈색세포종', category: '질환', tags: ['men2'] },
      { text: '부갑상선기능항진증', category: '질환', tags: ['men2'] }
    ]
  },
  {
    id: 'ibd',
    name: '염증성 장질환',
    subject: '소화기내과',
    tagLabels: {
      ibd: '염증성 장질환',
      crohn: '크론병',
      uc: '궤양성 대장염',
      extraint: '장외 증상',
      ibd_tx: 'IBD 치료',
      anti_tnf: '항TNF 제제',
      azathioprine: '아자티오프린',
      crc: '대장암 위험'
    },
    cards: [
      { text: '크론병', category: '질환', tags: ['crohn', 'ibd'] },
      { text: '궤양성 대장염', category: '질환', tags: ['uc', 'ibd'] },
      { text: '입~항문 분절성 병변 (skip lesion)', category: '병태생리', tags: ['crohn'] },
      { text: '직장에서 시작하는 연속성 병변', category: '병태생리', tags: ['uc'] },
      { text: '전층성 염증', category: '병태생리', tags: ['crohn'] },
      { text: '점막 · 점막하층 국한 염증', category: '병태생리', tags: ['uc'] },
      { text: '비건락성 육아종', category: '검사소견', tags: ['crohn'] },
      { text: '음와 농양 (crypt abscess)', category: '검사소견', tags: ['uc'] },
      { text: '자갈길 모양 (cobblestone)', category: '검사소견', tags: ['crohn'] },
      { text: '누공 · 협착', category: '합병증', tags: ['crohn'] },
      { text: '말단 회장 침범 → B12 흡수장애', category: '병태생리', tags: ['crohn'] },
      { text: '담석 · 옥살산칼슘 신장결석', category: '합병증', tags: ['crohn'] },
      { text: 'ASCA 양성', category: '검사소견', tags: ['crohn'] },
      { text: 'p-ANCA 양성', category: '검사소견', tags: ['uc'] },
      { text: '흡연 (크론 위험↑, UC 위험↓)', category: '위험인자', tags: ['crohn', 'uc'] },
      { text: '혈성 설사 · 뒤무직', category: '임상상', tags: ['uc'] },
      { text: '독성 거대결장', category: '합병증', tags: ['uc'] },
      { text: '원발성 경화성 담관염 (PSC)', category: '합병증', tags: ['uc', 'extraint'] },
      { text: '괴저농피증', category: '임상상', tags: ['extraint', 'uc'] },
      { text: '결절홍반', category: '임상상', tags: ['extraint', 'ibd'] },
      { text: '강직척추염 · 천장관절염', category: '임상상', tags: ['extraint', 'ibd'] },
      { text: '포도막염 · 공막염', category: '임상상', tags: ['extraint'] },
      { text: '대장내시경 + 조직검사', category: '진단', tags: ['ibd'] },
      { text: '장결핵 감별 필요', category: '진단', tags: ['crohn', 'anti_tnf'] },
      { text: '5-ASA (메살라진)', category: '치료', tags: ['ibd_tx', 'uc'] },
      { text: '코르티코스테로이드 (관해 유도)', category: '치료', tags: ['ibd_tx'] },
      { text: '아자티오프린 (관해 유지)', category: '치료', tags: ['ibd_tx', 'azathioprine'] },
      { text: 'TPMT 활성 검사', category: '진단', tags: ['azathioprine'] },
      { text: '골수억제 · 췌장염', category: '합병증', tags: ['azathioprine'] },
      { text: '인플릭시맙 · 아달리무맙', category: '치료', tags: ['anti_tnf', 'ibd_tx', 'crohn'] },
      { text: '잠복결핵 검사 (IGRA)', category: '진단', tags: ['anti_tnf'] },
      { text: 'B형간염 선별검사', category: '진단', tags: ['anti_tnf', 'azathioprine'] },
      { text: '전대장절제술 (완치적)', category: '치료', tags: ['uc'] },
      { text: '대장암 위험 증가', category: '합병증', tags: ['crc', 'ibd'] },
      { text: '발병 8년 후부터 감시 대장내시경', category: '진단', tags: ['crc'] },
      { text: 'PSC 동반 시 진단 즉시 감시 시작', category: '진단', tags: ['crc', 'extraint'] }
    ]
  }
];
